[frontend]
epicbook_frontend ansible_host=34.237.145.113 ansible_user=ubuntu

[backend]
epicbook_backend ansible_host=10.0.2.157 ansible_user=ubuntu ansible_ssh_common_args="-o ProxyCommand=\"ssh -W %h:%p -i /path/to/key ubuntu@34.237.145.113\""