[frontend]
epicbook_frontend ansible_host=34.237.145.113

[frontend:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/epic_ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[Backend]
epicbook_backend ansible_host=13.219.235.66

[Backend:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/epic_ssh/id_ed25519
#ansible_ssh_common_args='-o ProxyJump=ubuntu@34.237.145.113 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3